FROM ubuntu:xenial

RUN mkdir ./home/TensorFlow
WORKDIR ./home/TensorFlow
RUN mkdir ./src
COPY ./src ./src

RUN apt-get update && apt-get install -y wget
CMD wget https://www.python.org/ftp/python/$version/Python-2.7.13.tgz && tar -xvf Python-2.7.13.tgz && cd Python-2.7.13 && ./configure && make
CMD ["python", "./src/HelloWorld.py"]
